In [14]:
import pandas as pd

In [15]:
df = pd.read_csv("https://raw.githubusercontent.com/atlantico-academy/datasets/main/mpg.csv")
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [16]:
df.to_csv("../data/raw/data.csv", index=False)

In [17]:
dicionario = pd.DataFrame([
    {
        "variavel": "mpg",
        "descricao": "Autonomia em milhas por galão",
        "tipo":"quantitativa",
        "subtipo":"continua"
    },{
        "variavel": "cylinders",
        "descricao": "Quantidade de cilindros",
        "tipo":"quantitativa",
        "subtipo":"continua"
    },{
        "variavel": "displacement",
        "descricao": "Volume de gás dentro do pistão ",
        "tipo":"quantitativa",
        "subtipo":"continua"
    },{
        "variavel": "horsepower",
        "descricao": "Potência do motor",
        "tipo":"quantitativa",
        "subtipo":"continua"
    },{
        "variavel": "weight",
        "descricao": "Peso do veículo",
        "tipo":"quantitativa",
        "subtipo":"continua"
    },{
        "variavel": "acceleration",
        "descricao": "Tempo de aceleração do veículo",
        "tipo":"quantitativa",
        "subtipo":"continua"
    },{
        "variavel": "model_year",
        "descricao": "Ano de fabricação",
        "tipo":"qualitativa",
        "subtipo":"continua"
    },{
        "variavel": "origin",
        "descricao": "País de origem do veículo",
        "tipo":"qualitativa",
        "subtipo":"nominal"
    },{
        "variavel": "name",
        "descricao": "Modelo do carro",
        "tipo":"qualitativa",
        "subtipo":"nominal"
    }
])
dicionario.to_csv('../data/external/dictionary.csv', index=False)
dicionario

       variavel                        descricao          tipo   subtipo
0           mpg    Autonomia em milhas por galão  quantitativa  continua
1     cylinders          Quantidade de cilindros  quantitativa  continua
2  displacement  Volume de gás dentro do pistão   quantitativa  continua
3    horsepower                Potência do motor  quantitativa  continua
4        weight                  Peso do veículo  quantitativa  continua
5  acceleration   Tempo de aceleração do veículo  quantitativa  continua
6    model_year                Ano de fabricação   qualitativa  continua
7        origin        País de origem do veículo   qualitativa   nominal
8          name                  Modelo do carro   qualitativa   nominal